#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/4c39b776-31bf-4321-8395-2e72ff4a7ccb/ # 
title: Book Service API
version: 1.0

/authors:
  description: This is used to get authors details
  get:
    responses: 
      200:
        body:
          application/json:
            example:         
  /{authorID}:
    get:
      responses: 
        200:
          body: 
            application/json:
              example: 
        404:
          body:
            application/json:
              example:    